# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Vsquared
tagline:             'Machined thoughts'
description:         'Machine learning, data science, and all other forms of alchemy.'
url:                 https://jeremyvsquared.github.io/
baseurl:             'https://jeremyvsquared.github.io/'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
